@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.3.0/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.3.0/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.3.0/C4_Component.puml

Component(main_component, "main", "Rust module", "Main entry point of the program. Parses model parameters from the command-line.")
Component(gui_component, "gui", "Rust module", "Main program loop containing a graphical user interface. Handles user input and simulation controls (change speed/reset/...)")
Component(stats_component, "stats", "Rust module", "Collects information about the model and records the data in an export file")
Component(model_component, "model", "Rust module", "Model of a grid world containing cells with different rules")
Component(gfx_component, "gfx", "Rust module", "Visualizes the model state onto a graphical buffer")

Rel(main_component, gui_component, "Uses")

Rel(gui_component, model_component, "Uses")
Rel(gui_component, gfx_component, "Uses")
Rel(gui_component, stats_component, "Uses")

@enduml