@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.3.0/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.3.0/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.3.0/C4_Component.puml

Component(main_component, "main", "Rust module", "Main entry point of the program. Parses model parameters from the command-line.")
Component(gui_component, "gui", "Rust module", "Main program loop containing a graphical user interface. Handles user input and simulation controls")
Component(gfx_component, "gfx", "Rust module", "Visualizes the model state onto a graphical buffer")
Component(stats_component, "stats", "Rust module", "Collects information about the model and records the data in an export file")

Component(params_component, "params", "Rust module", "Contains model parameter definitions and methods to import parameters from an external file")
Component(models_component, "models", "Rust module", "Provides the base interface for a predator-prey cellular automata-based model")
Component(simple_model_component, "simple_model", "Rust module", "An implementation of Human's 'simple model', extended with foodweb relations")
Component(pppe_model_component, "pppe_model", "Rust module", "An implementation of Human's PPPE model, extended with foodweb relations")
Component(dsam_model_component, "dsam_model", "Rust module", "An implementation of Human's DSAM model, extended with foodweb relations")
Component(custom_model_component, "custom_model", "Rust module", "A custom cellular automata model, including foodweb relations")

Rel(main_component, gui_component, "Uses")

Rel(models_component, simple_model_component, "Uses")
Rel(models_component, pppe_model_component, "Uses")
Rel(models_component, dsam_model_component, "Uses")
Rel(models_component, custom_model_component, "Uses")
Rel_L(models_component, params_component, "Uses")

Rel(gui_component, models_component, "Uses")
Rel(gui_component, gfx_component, "Uses")
Rel(gui_component, stats_component, "Uses")

@enduml